### PR TITLE
fixed Rosette installation in FrontendDockerfile

### PR DESCRIPTION
**Pull request by primeapple**
As suggested I created a pull request.
I tested the changes with the test_in_docker.sh file, they work correctly.

With the old file, failures occured.

A full explanation of the changes is found in #68 

Please review and merge. Tell me your thoughts!

### CODE REVIEW

**Comment by stechu** [comment]
It appears that the travis-CI failed.
Would you mind taking a look? If not, I can take a look later this week.

**Comment by primeapple** [comment]
Of course I will have a look :)

The problem is that the dockerimage for Cosette-Frontend is pulled from shumo/cosette-frontend (dockerhub). However this image is build with the exact wrong dockerfile, that I propose to fix in this PR.

We could solve this by merge this PR and update the dockerfile in shumo/cosette-frontend (see [here](https://hub.docker.com/r/shumo/cosette-frontend/~/dockerfile/)) to the version that I created here :)

**Comment by akcheung** [comment]
Thanks @primeapple . I have merged your PR manually on my local repo and it passed the regression tests.

**Comment by stechu** [comment]
I see. That's the circular dependency issue (that file in docker hub actually linked here as well).

**Comment by stechu** [comment]
Restart CI test after new docker image is up. Now the CI test passes. Thanks @primeapple !

**Pull request merged**
